---
theme: dark
jwt_secret: a_very_secure_jwt_secret_key_homelab
default_redirection_url: https://auth.homelab.lan

server:
  host: 0.0.0.0
  port: 9091

log:
  level: info

totp:
  issuer: homelab.lan

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id

access_control:
  default_policy: deny
  rules:
    - domain: "*.homelab.lan"
      policy: two_factor
