---
all:
  hosts:
    cyber-node01:
      ansible_host: 192.168.64.10
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    cyber-node02:
      ansible_host: 192.168.64.20
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519

  children:
    hardened_targets:
      hosts:
        - cyber-node01
    monitoring_nodes:
      hosts:
        - cyber-node02
