services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - PASSWORD=codeserver_password
    volumes:
      - ./config:/config
      - ./workspace:/config/workspace
    ports:
      - '8443:8443'
