version: "3.8"

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8095:8090"
    volumes:
      - ./pb_data:/pb_data
    networks:
      - arm-net

networks:
  arm-net:
    external: true
