services:
  proxmox-mail-gateway:
    image: alpine:latest
    container_name: proxmox-mail-gateway
    restart: unless-stopped
    ports:
      - "8006:8006"
      - "25:25"
    environment:
      - TZ=Europe/Bucharest
    command: ["sh", "-c", "while true; do sleep 3600; done"]
