# OPNsense Automated Encrypted Git Backup (os-git-backup)
git_repository = "git@gitea.homelab.local:stefanut/opnsense-config-backups.git"
git_branch = "main"
gpg_encryption = true
gpg_key_id = "0xSTEFANUT_SEC_KEY"
trigger_on_change = true
retention_days = 365
diff_tracking = true
