# OPNsense NetFlow / IPFIX Exporter Configuration
capture_interfaces = ["vtnet0", "vtnet1", "vlan10", "vlan20", "vlan30", "vlan40", "vlan50"]
egress_only = false
version = 9
destination_ip = "192.168.1.132" # Wazuh SIEM Telemetry Receiver
destination_port = 2055
active_timeout = 60
inactive_timeout = 15
