services:
  sonarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - ./config:/config
      - /mnt/media:/media
    ports:
      - "8989:8989"
    restart: unless-stopped
