version: "3.8"

services:
  tubearchivist:
    image: bbilly1/tubearchivist:latest
    container_name: tubearchivist
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - ES_URL=http://archivist-es:9200
      - REDIS_CON=redis://archivist-redis:6379
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=http://192.168.1.30:8000
      - TA_USERNAME=tubearchivist
      - TA_PASSWORD=tubepassword2026
      - ELASTIC_PASSWORD=elasticpassword2026
      - TZ=Europe/Bucharest
    volumes:
      - ./media:/youtube
      - ./cache:/cache
    depends_on:
      - archivist-redis
    networks:
      - core-net

  archivist-redis:
    image: redis:alpine
    container_name: archivist-redis
    restart: unless-stopped
    volumes:
      - ./redis:/data
    networks:
      - core-net

networks:
  core-net:
    external: true
