---
all:
  children:
    hypervisors:
      hosts:
        pve_primary_x64:
          ansible_host: 192.168.1.132
          ansible_user: root
          arch: x86_64
          hardware: "Intel Core i3-10100F / GTX 1050 Ti / 12GB RAM / 512GB SSD"
          role: primary-bare-metal-hypervisor

    kubernetes_workers:
      hosts:
        k8s_node_04:
          ansible_host: 192.168.1.18
          arch: x86_64
          hardware: "AMD Athlon II X2 220 / NVIDIA GeForce GTS 250 / 4GB RAM DDR3 / 80GB HDD"
          role: kubernetes-worker-node
          domain: k8s-node-04.lan

    virtual_machines:
      hosts:
        opnsense_vm:
          vmid: 200
          ansible_host: 192.168.1.134
          ansible_port: 8443
          node: pve_primary_x64
          role: core-firewall-router-ingress-proxy
          domain: opnsense.lan
        windows_server_vm:
          vmid: 201
          ansible_host: 192.168.1.132
          ansible_port: 3389
          node: pve_primary_x64
          os: windows-server-2025-x64
          memory_mb: 8192
          cores: 4
          disk_gb: 256
          role: enterprise-windows-server-active-directory
          domain: winserver.lan
        rhel_vm:
          vmid: 202
          ansible_host: 192.168.1.202
          node: pve_primary_x64
          os: rhel-9.8-x64
          memory_mb: 2048
          cores: 2
          disk_gb: 50
          role: redhat-enterprise-linux-workload
          domain: rhel.lan
        openstack_vm:
          vmid: 205
          ansible_host: 192.168.1.205
          node: pve_primary_x64
          os: ubuntu-24.04-openstack
          memory_mb: 4096
          cores: 2
          disk_gb: 32
          role: openstack-private-cloud-controller
          domain: openstack.lan
        metasploitable_vm:
          vmid: 206
          ansible_host: 192.168.1.206
          node: pve_primary_x64
          os: metasploitable-2
          memory_mb: 512
          cores: 1
          disk_gb: 8
          role: penetration-testing-vulnerable-target
          domain: metasploitable.lan
        tpot_vm:
          vmid: 207
          ansible_host: 192.168.1.207
          node: pve_primary_x64
          os: tpot-24.04
          memory_mb: 8192
          cores: 4
          disk_gb: 60
          role: honeypot-threat-intelligence-platform
          domain: tpot.lan
        securityonion_vm:
          vmid: 208
          ansible_host: 192.168.1.208
          node: pve_primary_x64
          os: securityonion-3.2
          memory_mb: 8192
          cores: 4
          disk_gb: 50
          role: siem-hids-network-security-monitoring
          domain: securityonion.lan
        remnux_vm:
          vmid: 209
          ansible_host: 192.168.1.209
          node: pve_primary_x64
          os: remnux-v7
          memory_mb: 4096
          cores: 2
          disk_gb: 40
          role: malware-reverse-engineering-forensics
          domain: remnux.lan
        windows_server_licenta_vm:
          vmid: 300
          ansible_host: 192.168.1.210
          node: pve_primary_x64
          os: windows-server-2019-standard
          memory_mb: 8192
          cores: 4
          disk_gb: 64
          role: enterprise-windows-server-licensed-workload
          domain: win2019.lan
        metasploitable_licenta_vm:
          vmid: 301
          ansible_host: 192.168.1.211
          node: pve_primary_x64
          os: metasploitable-linux
          memory_mb: 2048
          cores: 2
          disk_gb: 20
          role: penetration-testing-vulnerable-licensed-target
          domain: metasploitable.lan


    lxc_x64_core:
      hosts:
        immich_photos:
          vmid: 100
          ansible_host: 192.168.1.15
          domain: immich.lan
          memory_mb: 896
          disk_gb: 40
        nextcloud_hub:
          vmid: 101
          ansible_host: 192.168.1.8
          domain: nextcloud.lan
          memory_mb: 96
          disk_gb: 20

        homeassistant_core:
          vmid: 102
          ansible_host: 192.168.1.10
          domain: ha.lan
          memory_mb: 384
          disk_gb: 16
        n8n_automation:
          vmid: 103
          ansible_host: 192.168.1.13
          domain: n8n.lan
          memory_mb: 384
          disk_gb: 8
        scrutiny_smart_x64:
          vmid: 104
          ansible_host: 192.168.1.18
          domain: scrutiny.lan
          memory_mb: 96
          disk_gb: 4
        media_suite:
          vmid: 105
          ansible_host: 192.168.1.21
          domain: jellyfin.lan
          memory_mb: 896
          disk_gb: 50
