version: "3.8"

services:
  wallos:
    image: bellamy/wallos:latest
    container_name: wallos
    restart: unless-stopped
    environment:
      - TZ=Europe/Bucharest
    volumes:
      - ./db:/var/www/html/db
      - ./logos:/var/www/html/images/uploads/logos
    ports:
      - "8282:80"
    networks:
      - arm-net

networks:
  arm-net:
    external: true
