version: '3.8'

services:
  cyberchef:
    image: ghcr.io/gchq/cyberchef:latest
    container_name: cyberlab-cyberchef
    restart: unless-stopped
    ports:
      - "8088:80"
    networks:
      - soc-net

networks:
  soc-net:
    name: cyberlab-soc-net
