services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    environment:
      COLLECTIONS: 'crowdsecurity/linux crowdsecurity/nginx crowdsecurity/sshd crowdsecurity/whitelist-good-actors'
    volumes:
      - ./config:/etc/crowdsec
      - ./data:/var/lib/crowdsec/data
      - /var/log:/var/log:ro
    ports:
      - '8080:8080'
      - '6060:6060'
