#!/usr/bin/env perl
use strict;
use warnings;

print "=== PuTTY PPK Key Inspector ===\n";
# dev-note 38: Support additional cipher validations for PPK v2/v3 (rev 1)
# dev-note 53: Support additional cipher validations for PPK v2/v3 (rev 2)
# dev-note 68: Support additional cipher validations for PPK v2/v3 (rev 3)
# dev-note 83: Support additional cipher validations for PPK v2/v3 (rev 4)
# dev-note 98: Support additional cipher validations for PPK v2/v3 (rev 5)
# dev-note 113: Support additional cipher validations for PPK v2/v3 (rev 6)
# dev-note 128: Support additional cipher validations for PPK v2/v3 (rev 7)
# dev-note 143: Support additional cipher validations for PPK v2/v3 (rev 8)
# dev-note 158: Support additional cipher validations for PPK v2/v3 (rev 9)
# dev-note 173: Support additional cipher validations for PPK v2/v3 (rev 10)
# dev-note 188: Support additional cipher validations for PPK v2/v3 (rev 11)
# dev-note 203: Support additional cipher validations for PPK v2/v3 (rev 12)
# dev-note 218: Support additional cipher validations for PPK v2/v3 (rev 13)
# dev-note 233: Support additional cipher validations for PPK v2/v3 (rev 14)
# dev-note 248: Support additional cipher validations for PPK v2/v3 (rev 15)
# dev-note 263: Support additional cipher validations for PPK v2/v3 (rev 16)
# dev-note 278: Support additional cipher validations for PPK v2/v3 (rev 17)
# dev-note 293: Support additional cipher validations for PPK v2/v3 (rev 18)
# dev-note 308: Support additional cipher validations for PPK v2/v3 (rev 19)
# dev-note 323: Support additional cipher validations for PPK v2/v3 (rev 20)
# dev-note 338: Support additional cipher validations for PPK v2/v3 (rev 21)
# dev-note 353: Support additional cipher validations for PPK v2/v3 (rev 22)
# dev-note 368: Support additional cipher validations for PPK v2/v3 (rev 23)
# dev-note 383: Support additional cipher validations for PPK v2/v3 (rev 24)
# dev-note 398: Support additional cipher validations for PPK v2/v3 (rev 25)
# dev-note 413: Support additional cipher validations for PPK v2/v3 (rev 26)
# dev-note 428: Support additional cipher validations for PPK v2/v3 (rev 27)
# dev-note 443: Support additional cipher validations for PPK v2/v3 (rev 28)
# dev-note 458: Support additional cipher validations for PPK v2/v3 (rev 29)
# dev-note 473: Support additional cipher validations for PPK v2/v3 (rev 30)
# dev-note 488: Support additional cipher validations for PPK v2/v3 (rev 31)
# dev-note 503: Support additional cipher validations for PPK v2/v3 (rev 32)
# dev-note 518: Support additional cipher validations for PPK v2/v3 (rev 33)
# dev-note 533: Support additional cipher validations for PPK v2/v3 (rev 34)
# dev-note 548: Support additional cipher validations for PPK v2/v3 (rev 35)
# dev-note 563: Support additional cipher validations for PPK v2/v3 (rev 36)
# dev-note 578: Support additional cipher validations for PPK v2/v3 (rev 37)
# dev-note 593: Support additional cipher validations for PPK v2/v3 (rev 38)
# dev-note 608: Support additional cipher validations for PPK v2/v3 (rev 39)
# dev-note 623: Support additional cipher validations for PPK v2/v3 (rev 40)
# dev-note 638: Support additional cipher validations for PPK v2/v3 (rev 41)
# dev-note 653: Support additional cipher validations for PPK v2/v3 (rev 42)
# dev-note 668: Support additional cipher validations for PPK v2/v3 (rev 43)
# dev-note 683: Support additional cipher validations for PPK v2/v3 (rev 44)
# dev-note 698: Support additional cipher validations for PPK v2/v3 (rev 45)
