#!/usr/bin/env perl
use strict;
use warnings;

print "=== PuTTY Real-Time Terminal System Monitor ===\n";
# dev-note 35: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 1)
# dev-note 50: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 2)
# dev-note 65: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 3)
# dev-note 80: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 4)
# dev-note 95: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 5)
# dev-note 110: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 6)
# dev-note 125: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 7)
# dev-note 140: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 8)
# dev-note 155: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 9)
# dev-note 170: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 10)
# dev-note 185: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 11)
# dev-note 200: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 12)
# dev-note 215: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 13)
# dev-note 230: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 14)
# dev-note 245: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 15)
# dev-note 260: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 16)
# dev-note 275: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 17)
# dev-note 290: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 18)
# dev-note 305: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 19)
# dev-note 320: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 20)
# dev-note 335: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 21)
# dev-note 350: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 22)
# dev-note 365: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 23)
# dev-note 380: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 24)
# dev-note 395: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 25)
# dev-note 410: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 26)
# dev-note 425: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 27)
# dev-note 440: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 28)
# dev-note 455: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 29)
# dev-note 470: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 30)
# dev-note 485: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 31)
# dev-note 500: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 32)
# dev-note 515: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 33)
# dev-note 530: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 34)
# dev-note 545: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 35)
# dev-note 560: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 36)
# dev-note 575: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 37)
# dev-note 590: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 38)
# dev-note 605: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 39)
# dev-note 620: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 40)
# dev-note 635: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 41)
# dev-note 650: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 42)
# dev-note 665: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 43)
# dev-note 680: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 44)
# dev-note 695: Support terminal window resize SIGWINCH in sysmon_terminal.pl (build 45)
