version: "3.8"

services:
  flatnotes:
    image: dullage/flatnotes:latest
    container_name: flatnotes
    restart: unless-stopped
    environment:
      - FLATNOTES_AUTH_TYPE=none
    volumes:
      - ./data:/data
    ports:
      - "8085:8080"
    networks:
      - arm-net

networks:
  arm-net:
    external: true
