services:
  proxmox-backup-server:
    image: datanomike/proxmox-backup-server:latest
    container_name: proxmox-backup-server
    restart: unless-stopped
    ports:
      - "8007:8007"
    environment:
      - TZ=Europe/Bucharest
    volumes:
      - ./data:/etc/proxmox-backup
      - ./backup:/backup
