services:
  trilium:
    image: zedrr/trilium:latest
    container_name: trilium-notes
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - trilium-data:/home/node/trilium-data

volumes:
  trilium-data:
