version: "3.8"

services:
  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./data:/etc/linkding/data
    environment:
      - LD_ENABLE_AUTH_PROXY=false
    networks:
      - arm-net

networks:
  arm-net:
    external: true
