version: '3.8'

services:
  task-scam-infrastructure-analysis-web:
    build:
      context: ..
      dockerfile: web/Dockerfile
    image: ghcr.io/stefannut/task-scam-infrastructure-analysis-web:latest
    container_name: task-scam-infrastructure-analysis-web-hub
    restart: unless-stopped
    ports:
      - "8089:80"
    environment:
      - NODE_ENV=production
