---
services:
  vscode-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: vscode-server-arm
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - PASSWORD=Stefanut005
      - SUDO_PASSWORD=Stefanut005
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8443:8443"
