version: "3.8"

services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=0 * * * *
    volumes:
      - ./config:/config
    ports:
      - "8080:80"
    networks:
      - arm-net

networks:
  arm-net:
    external: true
