services:
  proxmox-datacenter-manager:
    image: alpine:latest
    container_name: proxmox-datacenter-manager
    restart: unless-stopped
    ports:
      - "8443:8443"
    environment:
      - TZ=Europe/Bucharest
      - PDM_HTTP_PORT=8443
      - CLUSTER_PVE1=192.168.1.132:8006
      - CLUSTER_PVE2=192.168.64.14:8006
      - STORAGE_PBS1=192.168.1.149:8007
      - STORAGE_PBS2=192.168.64.146:8007
    volumes:
      - ./data:/etc/proxmox-datacenter-manager

