services:
  renovate:
    image: renovate/renovate:latest
    container_name: renovatebot
    restart: unless-stopped
    environment:
      - RENOVATE_PLATFORM=gitea
      - RENOVATE_ENDPOINT=http://192.168.64.109:3000/api/v1
      - RENOVATE_TOKEN=gitea_token_secret_vault
      - RENOVATE_AUTODISCOVER=true
      - RENOVATE_SCHEDULE=["every weekend"]
      - LOG_LEVEL=info
    volumes:
      - ./config.js:/usr/src/app/config.js:ro
      - ./cache:/tmp/renovate/cache
