version: "3.8"

services:
  drawio:
    image: jgraph/drawio:latest
    container_name: drawio
    restart: unless-stopped
    ports:
      - "8082:8080"
    networks:
      - core-net

networks:
  core-net:
    external: true
