from __future__ import annotations
from typing import List, Dict, Any

# Complete Homelab Services & Infrastructure Inventory extracted from homelab-soc
HOMELAB_SERVICES: List[Dict[str, Any]] = [
    {
        "id": "nginx-proxy-manager",
        "name": "Nginx Proxy Manager",
        "category": "networking",
        "ip": "192.168.1.3",
        "port": 81,
        "domain": "nginx.lan",
        "container": "npm",
        "lxc_vmid": 100,
        "status": "online",
        "tags": ["Reverse Proxy", "SSL", "Let's Encrypt", "Ingress"],
        "description": "Reverse proxy management dashboard providing automated SSL and local domain routing."
    },
    {
        "id": "pi-hole",
        "name": "Pi-hole DNS Sinkhole & Adblock",
        "category": "networking",
        "ip": "192.168.1.4",
        "port": 8080,
        "domain": "pihole.lan",
        "container": "pihole",
        "lxc_vmid": 101,
        "status": "online",
        "tags": ["DNS", "Adblock", "FTL Engine", "Wildcards"],
        "description": "Network-wide DNS sinkhole, tracker blocker, and local authoritative DNS server."
    },
    {
        "id": "opnsense",
        "name": "OPNsense Core Gateway",
        "category": "security",
        "ip": "192.168.1.1",
        "port": 443,
        "domain": "opnsense.lan",
        "container": "VM 200",
        "lxc_vmid": 200,
        "status": "online",
        "tags": ["Firewall", "Suricata IDS", "VLAN Routing", "BGP"],
        "description": "Enterprise router, stateful firewall, Suricata intrusion prevention, and VLAN isolation."
    },
    {
        "id": "homeassistant",
        "name": "Home Assistant Core",
        "category": "iot",
        "ip": "192.168.1.10",
        "port": 8123,
        "domain": "ha.lan",
        "container": "homeassistant",
        "lxc_vmid": 107,
        "status": "online",
        "tags": ["Smart Home", "Automations", "IoT", "Zigbee", "MQTT"],
        "description": "Central smart home automation platform integrating ESP32 nodes, Shelly relays, and sensors."
    },
    {
        "id": "immich",
        "name": "Immich Photos & Video",
        "category": "cloud",
        "ip": "192.168.1.15",
        "port": 2283,
        "domain": "immich.lan",
        "container": "immich_server",
        "lxc_vmid": 103,
        "status": "online",
        "tags": ["Photos", "AI Clustering", "CLIP Search", "Mobile Backup"],
        "description": "Self-hosted photo and video backup platform with AI facial recognition and semantic search."
    },
    {
        "id": "vaultwarden",
        "name": "Vaultwarden Password Vault",
        "category": "security",
        "ip": "192.168.1.16",
        "port": 8080,
        "domain": "vaultwarden.lan",
        "container": "vaultwarden",
        "lxc_vmid": 112,
        "status": "online",
        "tags": ["Passwords", "2FA", "TOTP", "Zero-Knowledge"],
        "description": "Zero-knowledge encrypted Bitwarden-compatible vault for credentials and secrets."
    },
    {
        "id": "nextcloud",
        "name": "Nextcloud Hub",
        "category": "cloud",
        "ip": "192.168.1.8",
        "port": 80,
        "domain": "nextcloud.lan",
        "container": "nextcloud",
        "lxc_vmid": 105,
        "status": "online",
        "tags": ["Storage", "WebDAV", "Collabora", "File Sync"],
        "description": "Private cloud document management, collaboration suite, and file synchronization."
    },
    {
        "id": "grafana",
        "name": "Grafana Telemetry",
        "category": "monitoring",
        "ip": "192.168.1.11",
        "port": 3000,
        "domain": "grafana.lan",
        "container": "grafana",
        "lxc_vmid": 108,
        "status": "online",
        "tags": ["Metrics", "Dashboards", "Prometheus", "Loki"],
        "description": "Central visualization platform aggregating hardware metrics, Loki logs, and container health."
    },
    {
        "id": "prometheus",
        "name": "Prometheus TSDB Engine",
        "category": "monitoring",
        "ip": "192.168.1.11",
        "port": 9090,
        "domain": "prometheus.lan",
        "container": "prometheus",
        "lxc_vmid": 108,
        "status": "online",
        "tags": ["Time Series", "Metrics", "Node-Exporter"],
        "description": "High-efficiency time-series metric collector scraping hardware and hypervisor statistics."
    },
    {
        "id": "loki",
        "name": "Grafana Loki Log Engine",
        "category": "monitoring",
        "ip": "192.168.1.11",
        "port": 3100,
        "domain": "loki.lan",
        "container": "loki",
        "lxc_vmid": 108,
        "status": "online",
        "tags": ["Logs", "Promtail", "LogQL", "Audit"],
        "description": "Horizontally-scalable log aggregation system indexing syslog and container logs."
    },
    {
        "id": "uptime-kuma",
        "name": "Uptime Kuma Status Monitor",
        "category": "monitoring",
        "ip": "192.168.1.7",
        "port": 3001,
        "domain": "uptime.lan",
        "container": "uptime-kuma",
        "lxc_vmid": 104,
        "status": "online",
        "tags": ["Uptime", "Ping", "Status Page", "Alerts"],
        "description": "Status monitoring tracking HTTP response times, ports, and SSL validity with push alerts."
    },
    {
        "id": "n8n",
        "name": "n8n Workflow Automation",
        "category": "automation",
        "ip": "192.168.1.13",
        "port": 5678,
        "domain": "n8n.lan",
        "container": "n8n",
        "lxc_vmid": 110,
        "status": "online",
        "tags": ["Workflows", "No-Code", "Webhooks", "Pipelines"],
        "description": "Low-code workflow automation orchestrating API calls, MQTT triggers, and backup routines."
    },
    {
        "id": "gitea",
        "name": "Gitea Git Forge",
        "category": "devops",
        "ip": "192.168.1.17",
        "port": 3000,
        "domain": "gitea.lan",
        "container": "gitea",
        "lxc_vmid": 113,
        "status": "online",
        "tags": ["Git", "Repositories", "GitOps", "Actions"],
        "description": "Lightweight self-hosted Git version control forge supporting pull requests and webhooks."
    },
    {
        "id": "woodpecker-ci",
        "name": "Woodpecker CI Engine",
        "category": "devops",
        "ip": "192.168.1.14",
        "port": 8000,
        "domain": "woodpecker.lan",
        "container": "woodpecker-server",
        "lxc_vmid": 111,
        "status": "online",
        "tags": ["CI/CD", "Docker Pipelines", "Automated Testing"],
        "description": "Container-native CI engine executing automated linting, test suites, and Docker builds."
    },
    {
        "id": "authelia",
        "name": "Authelia 2FA & SSO",
        "category": "security",
        "ip": "192.168.1.20",
        "port": 9091,
        "domain": "authelia.lan",
        "container": "authelia",
        "lxc_vmid": 116,
        "status": "online",
        "tags": ["SSO", "2FA", "OIDC", "Forward Auth"],
        "description": "Single Sign-On and multi-factor authentication portal safeguarding reverse proxy ingress."
    },
    {
        "id": "crowdsec",
        "name": "CrowdSec Cyber Defense",
        "category": "security",
        "ip": "192.168.1.9",
        "port": 8080,
        "domain": "crowdsec.lan",
        "container": "crowdsec",
        "lxc_vmid": 109,
        "status": "online",
        "tags": ["IPS", "Threat Intelligence", "Brute-Force Protection"],
        "description": "Behavioral intrusion prevention system analyzing Nginx/SSH logs to auto-ban malicious IPs."
    },
    {
        "id": "jellyfin",
        "name": "Jellyfin Media Server",
        "category": "media",
        "ip": "192.168.1.21",
        "port": 8096,
        "domain": "jellyfin.lan",
        "container": "jellyfin",
        "lxc_vmid": 117,
        "status": "online",
        "tags": ["Media Server", "Streaming", "Transcoding", "DLNA"],
        "description": "Media streaming server with multi-user profiles, subtitle syncing, and hardware acceleration."
    },
    {
        "id": "servarr-suite",
        "name": "Servarr Media Automation (Radarr / Sonarr / Prowlarr / Bazarr / qBit)",
        "category": "media",
        "ip": "192.168.1.21",
        "port": 7878,
        "domain": "servarr.lan",
        "container": "servarr_stack",
        "lxc_vmid": 117,
        "status": "online",
        "tags": ["Radarr", "Sonarr", "Prowlarr", "Bazarr", "qBittorrent"],
        "description": "Complete media management and download automation stack deployed on LXC 117."
    },
    {
        "id": "actualbudget",
        "name": "Actual Budget",
        "category": "productivity",
        "ip": "192.168.1.22",
        "port": 5006,
        "domain": "actualbudget.lan",
        "container": "actualbudget",
        "lxc_vmid": 118,
        "status": "online",
        "tags": ["Finance", "Budgeting", "Envelope System", "Encrypted"],
        "description": "Privacy-focused envelope budgeting application with client-side encrypted sync."
    },
    {
        "id": "trillium-notes",
        "name": "Trilium Knowledge Base",
        "category": "productivity",
        "ip": "192.168.1.19",
        "port": 8080,
        "domain": "trilium.lan",
        "container": "trilium",
        "lxc_vmid": 115,
        "status": "online",
        "tags": ["Notes", "Knowledge Base", "Markdown", "MathJax"],
        "description": "Hierarchical note-taking system for personal knowledge management with encryption."
    },
    {
        "id": "scrutiny",
        "name": "Scrutiny S.M.A.R.T. Drive Health",
        "category": "monitoring",
        "ip": "192.168.1.18",
        "port": 8080,
        "domain": "scrutiny.lan",
        "container": "scrutiny",
        "lxc_vmid": 114,
        "status": "online",
        "tags": ["S.M.A.R.T.", "SSD Endurance", "Temperature", "Storage Health"],
        "description": "Hard drive health dashboard tracking S.M.A.R.T. metrics and SSD wear percentages."
    },
    {
        "id": "academic-erp",
        "name": "Academic ERP & Monte Carlo Engine",
        "category": "business",
        "ip": "192.168.20.15",
        "port": 5000,
        "domain": "erp.lan",
        "container": "academic_erp",
        "lxc_vmid": 120,
        "status": "online",
        "tags": ["ERP", "CRM", "Monte Carlo", "Risk Simulation", "Crypto"],
        "description": "Academic business logic, financial portfolio risk modeling, and CRM customer records."
    }
]

HOMELAB_NODES: List[Dict[str, Any]] = [
    {
        "id": "apple-m1-compute",
        "name": "Apple M1 Node (Local Host)",
        "role": "Local Host • ARM64 Compute & ELO Core Runtime",
        "ip": "127.0.0.1 (MacBook-Air.local)",
        "is_local_host": True,
        "status": "ONLINE",
        "workloads": "ELO Core Daemon, Local ML Accelerators, Metal MPS"
    },
    {
        "id": "pve-node-1",
        "name": "Proxmox VE Hypervisor",
        "role": "Core Hypervisor & Virtualization",
        "ip": "192.168.10.2",
        "probe_ports": [8006, 22, 9100],
        "is_local_host": False,
        "status": "probe",
        "workloads": "LXC 100-119, VM 200 (OPNsense), VM 201 (Alpine)"
    },
    {
        "id": "openmediavault-nas",
        "name": "OpenMediaVault NAS",
        "role": "Storage & ZFS Backup Pools",
        "ip": "192.168.10.3",
        "probe_ports": [80, 445, 22, 9100],
        "is_local_host": False,
        "status": "probe",
        "workloads": "ZFS Pools, NFS / SMB Shares, BorgBackup"
    }
]
