---
services_base_path: "/opt"

docker_compose_version: "v2"
docker_network_name: "pve1.stefanut"

default_timezone: "Europe/Bucharest"
manage_python: true

homelab_services:
  - actualbudget
  - alist
  - changedetection.io
  - crowdsec
  - filebrowser
  - gitea
  - grafana
  - homeassistant
  - immich
  - it-tools
  - n8n
  - nextcloud
  - nginx
  - pi-hole
  - prometheus
  - scrutiny
  - trillium-notes
  - uptime-kuma
  - vaultwarden
  - woodpecker-ci

deploy_user: "root"
