services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    restart: unless-stopped
    environment:
      - GOTIFY_DEFAULTUSER_NAME=admin
      - GOTIFY_DEFAULTUSER_PASS=gotify_admin_pass
    volumes:
      - ./data:/app/data
    ports:
      - '8080:80'
