version: "3.8"

services:
  meilisearch:
    image: getmeili/meilisearch:v1.8
    container_name: meilisearch
    restart: unless-stopped
    ports:
      - "7700:7700"
    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=master_secret_key_homelab_2026
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./data.ms:/meili_data
    networks:
      - core-net

networks:
  core-net:
    external: true
