services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale-x64
    restart: unless-stopped
    network_mode: host
    environment:
      TS_AUTHKEY: 'tskey-auth-dummy-replace-in-env'
      TS_ROUTES: '192.168.1.0/24'
      TS_EXTRA_ARGS: '--advertise-exit-node'
      TS_STATE_DIR: '/var/lib/tailscale'
    volumes:
      - ./state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
