version: "3.8"

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - PASSWORD=homelab_vscode_password_2026
      - SUDO_PASSWORD=homelab_sudo_password_2026
    volumes:
      - ./config:/config
      - /homelab:/workspace
    ports:
      - "8443:8443"
    networks:
      - core-net

networks:
  core-net:
    external: true
