---
services:
  alist:
    image: xhofe/alist:v3.36.0
    container_name: alist
    restart: unless-stopped
    volumes:
      - ./data:/opt/alist/data
      - /mnt/storage:/mnt/storage
    ports:
      - "5244:5244"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
