services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_server
    restart: unless-stopped
    ports:
      - '2283:2283'
    environment:
      DB_HOSTNAME: immich_postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgrespassword
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: immich_redis
    volumes:
      - ./photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - immich-redis
      - immich-postgres

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich_machine_learning
    restart: unless-stopped
    volumes:
      - ./model-cache:/cache

  immich-redis:
    image: redis:6.2-alpine
    container_name: immich_redis
    restart: unless-stopped

  immich-postgres:
    image: tensorchord/pgvecto-rs:pg16-v0.2.1
    container_name: immich_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
    volumes:
      - ./pgdata:/var/lib/postgresql/data
