services:
  paperless-ai:
    image: clusterzx/paperless-ai:latest
    container_name: paperless-ai
    restart: unless-stopped
    environment:
      - PAPERLESS_API_URL=http://192.168.1.16:8005/api
      - PAPERLESS_API_TOKEN=your_token_here
      - AI_PROVIDER=ollama
      - OLLAMA_URL=http://192.168.1.110:11434
    ports:
      - '3000:3000'
