services:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    restart: unless-stopped
    ports:
      - '8086:8080'
    environment:
      SCRUTINY_WEB: 'true'
      SCRUTINY_COLLECTOR: 'true'
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
