version: "3.8"

services:
  your_spotify_server:
    image: yooooomi/your_spotify_server:latest
    container_name: your_spotify_server
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      - API_ENDPOINT=http://192.168.64.135:8082
      - CLIENT_ENDPOINT=http://192.168.64.135:3000
      - SPOTIFY_PUBLIC=spotify_client_id_placeholder
      - SPOTIFY_SECRET=spotify_client_secret_placeholder
      - CORS=all
    networks:
      - arm-net

networks:
  arm-net:
    external: true
