services:
  flowise:
    image: flowiseai/flowise:latest
    container_name: flowise
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    volumes:
      - ./data:/root/.flowise
