---
# ==============================================================================
# Global Variables — Enterprise CyberLab
# ==============================================================================

lab_domain: cyberlab.local
timezone: "Europe/Bucharest"
ntp_servers:
  - "0.ro.pool.ntp.org"
  - "1.ro.pool.ntp.org"
  - "time.cloudflare.com"

# Logging & Telemetry Endpoint
loki_server_url: "http://192.168.64.30:3100"
promtail_scrape_interval: 5s

# Core packages required across all nodes
common_packages:
  - curl
  - wget
  - git
  - htop
  - net-tools
  - iproute2
  - tcpdump
  - lsof
  - strace
  - auditd
  - audispd-plugins
  - fail2ban
  - ufw
  - chrony
  - jq
  - unattended-upgrades
