- id: '1721160000000'
  alias: "ALERT PVE1"
  description: "NOTIFICARE PVE1"
  trigger:
    - platform: state
      entity_id: binary_sensor.pve1_status
      to: 'off'
  action:
    - service: notify.mobile_app_owner
      data:
        message: "PVE1 is down!"
