version: '3.8'

services:
  openid-mitm-phishing-forensics:
    build:
      context: .
      dockerfile: web/Dockerfile
    image: ghcr.io/stefannut/openid-mitm-phishing-forensics-web:latest
    container_name: openid-mitm-phishing-forensics-web-service
    restart: unless-stopped
    ports:
      - "8087:80"
