services:
  searxng-redis:
    image: valkey/valkey:8-alpine
    container_name: searxng-cache
    restart: unless-stopped
    command: valkey-server --save "" --appendonly no
    ports:
      - '6379:6379'
