version: "3.8"

services:
  shiori:
    image: radseq/shiori:latest
    container_name: shiori
    restart: unless-stopped
    environment:
      - SHIORI_DIR=/srv/shiori
    volumes:
      - ./data:/srv/shiori
    ports:
      - "8089:8080"
    networks:
      - arm-net

networks:
  arm-net:
    external: true
