apiVersion: v1
kind: Namespace
metadata:
  name: woodpecker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: woodpecker-server
  namespace: woodpecker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: woodpecker-server
  template:
    metadata:
      labels:
        app: woodpecker-server
    spec:
      containers:
        - name: server
          image: woodpeckerci/woodpecker-server:v2.7.2
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 9000
              name: grpc
          env:
            - name: WOODPECKER_OPEN
              value: "true"
            - name: WOODPECKER_ADMIN
              value: "stefanut"
            - name: WOODPECKER_HOST
              value: "https://ci-x64.homelab.local"
            - name: WOODPECKER_SERVER_ADDR
              value: ":8000"
            - name: WOODPECKER_GRPC_ADDR
              value: ":9000"
            - name: WOODPECKER_GITEA
              value: "true"
            - name: WOODPECKER_GITEA_URL
              value: "http://192.168.64.109:3000"
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: woodpecker-agent
  namespace: woodpecker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: woodpecker-agent
  template:
    metadata:
      labels:
        app: woodpecker-agent
    spec:
      containers:
        - name: agent
          image: woodpeckerci/woodpecker-agent:v2.7.2
          env:
            - name: WOODPECKER_SERVER
              value: "woodpecker-server:9000"
            - name: WOODPECKER_MAX_WORKFLOWS
              value: "2"
            - name: WOODPECKER_BACKEND
              value: "kubernetes"
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: woodpecker-server
  namespace: woodpecker
spec:
  selector:
    app: woodpecker-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 9000
      targetPort: 9000
