version: "3.8"

services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    command: serve
    environment:
      - NTFY_BASE_URL=https://ntfy.homelab.local
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/user.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_BEHIND_PROXY=true
    volumes:
      - ./cache:/var/cache/ntfy
      - ./auth:/var/lib/ntfy
      - ./etc:/etc/ntfy
    ports:
      - "8081:80"
    networks:
      - arm-net

networks:
  arm-net:
    external: true
