version: '3.8'

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v2.4.1
    container_name: cyberlab-woodpecker-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=http://cyber-ctrl:8000
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=http://cyber-ctrl:3001
      - WOODPECKER_AGENT_SECRET=CyberLabSecretAgentKey123!
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker
    networks:
      - soc-net

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v2.4.1
    container_name: cyberlab-woodpecker-agent
    restart: unless-stopped
    command: agent
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=CyberLabSecretAgentKey123!
      - WOODPECKER_MAX_WORKFLOWS=2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - woodpecker-server
    networks:
      - soc-net

volumes:
  woodpecker-server-data:

networks:
  soc-net:
    name: cyberlab-soc-net
