version: '3.8'

services:
  putty-admin-tools:
    build: .
    image: ghcr.io/stefannut/putty-admin-scripts:latest
    container_name: putty-admin-toolkit
    restart: unless-stopped
    volumes:
      - .:/app
