version: "3.8"

services:
  wallabag:
    image: wallabag/wallabag:latest
    container_name: wallabag
    restart: unless-stopped
    ports:
      - "8084:80"
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.homelab.local
      - SYMFONY__ENV__SERVER_NAME="Homelab Wallabag"
    volumes:
      - ./images:/var/www/wallabag/web/assets/images
      - ./data:/var/www/wallabag/data
    networks:
      - arm-net

networks:
  arm-net:
    external: true
