version: v1alpha1
debug: false
persist: true
machine:
  type: controlplane
  token: 10100f.m1utmarm64talosk8s
  ca:
    crt: ""
    key: ""
  features:
    rbac: true
    stableHostname: true
    apidCheckEndpoints: true
  network:
    interfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 192.168.1.18/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.132
  install:
    disk: /dev/sda
    image: factory.talos.dev/installer/376567988ad370138ad0b26c9f59fc87b881a4ddb3f40eda8296079f50f2337b:v1.8.0
    bootloader: true
    wipe: false
  sysctls:
    kernel.kptr_restrict: "2"
    kernel.dmesg_restrict: "1"
    net.ipv4.tcp_syncookies: "1"
cluster:
  name: homelab-talos-cluster
  controlPlane:
    endpoint: https://192.168.1.18:6443
  network:
    cni:
      name: custom
      urls:
        - https://raw.githubusercontent.com/cilium/cilium/v1.16.1/install/kubernetes/quick-install.yaml
