server:
  host: 0.0.0.0
  port: 9091

log:
  level: info

identity_validation:
  reset_password:
    jwt_secret: a_very_secure_jwt_secret

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: '*.homelab.local'
      policy: two_factor
