apiVersion: v1
kind: Namespace
metadata:
  name: twingate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twingate-connector
  namespace: twingate
  labels:
    app: twingate-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twingate-connector
  template:
    metadata:
      labels:
        app: twingate-connector
    spec:
      containers:
        - name: connector
          image: twingate/connector:1
          env:
            - name: TWINGATE_NETWORK
              value: "homelab-privatenet"
            - name: TWINGATE_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twingate-secrets
                  key: access-token
                  optional: true
            - name: TWINGATE_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twingate-secrets
                  key: refresh-token
                  optional: true
            - name: TWINGATE_LOG_LEVEL
              value: "3"
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
