# OPNsense Tailscale Zero-Trust Subnet Router (os-tailscale)
tailscale_auth_key = "${TAILSCALE_EPHEMERAL_AUTH_KEY}"
hostname = "opnsense-gw"
advertise_routes = [
  "192.168.1.0/24",  # Primary LAN
  "192.168.10.0/24", # VLAN 10: Management & Hypervisors
  "192.168.20.0/24", # VLAN 20: Trusted Workloads & Databases
  "192.168.30.0/24", # VLAN 30: IoT & Edge Sensor Telemetry
  "192.168.40.0/24", # VLAN 40: DMZ & Public Ingress
  "192.168.50.0/24"  # VLAN 50: Security Onion / Honeypot Sandbox
]
accept_routes = true
exit_node = true
ssh = true
