version: '3.8'

services:
  cyberlab:
    build:
      context: .
      dockerfile: web/Dockerfile
    image: ghcr.io/stefannut/cyberlab-web:latest
    container_name: cyberlab-web-service
    restart: unless-stopped
    ports:
      - "8086:80"
