version: "3.8"

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.12.0
    container_name: mealie
    restart: unless-stopped
    ports:
      - "9925:9000"
    environment:
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - BASE_URL=https://mealie.homelab.local
    volumes:
      - ./mealie-data:/app/data/
    networks:
      - arm-net

networks:
  arm-net:
    external: true
