---
services:
  filebrowser:
    image: filebrowser/filebrowser:v2.30.0
    container_name: filebrowser
    restart: unless-stopped
    user: 1000:1000
    ports:
      - "8082:80"
    volumes:
      - /mnt/storage/shared:/srv
      - ./database/filebrowser.db:/database/filebrowser.db
      - ./.filebrowser.json:/.filebrowser.json:ro
