# k0s - Zero Friction Kubernetes Configuration for Node 1 CT 118 (Alpine Linux LXC)
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: k0s-woodpecker-x64
spec:
  api:
    address: 192.168.1.118
    port: 6443
    k0sApiPort: 9443
    sans:
      - 192.168.1.118
      - ci-x64.homelab.local
      - 127.0.0.1
  storage:
    type: etcd
  network:
    provider: kuberouter
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
  telemetry:
    enabled: false
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
  konnectivity:
    agentPort: 8132
    adminPort: 8133
