services:
  faster-whisper:
    image: fedirz/faster-whisper-server:latest-cuda
    container_name: faster-whisper
    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      WHISPER_MODEL: 'Systran/faster-whisper-small'
      WHISPER_DEVICE: 'cuda'
    volumes:
      - ./cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
