version: "3.8"

services:
  vikunja:
    image: vikunja/vikunja:latest
    container_name: vikunja
    restart: unless-stopped
    ports:
      - "3456:3456"
    environment:
      - VIKUNJA_SERVICE_TIMEZONE=Europe/Bucharest
      - VIKUNJA_DATABASE_TYPE=sqlite
      - VIKUNJA_SERVICE_JWTSECRET=vikunja_secret_key_2026
    volumes:
      - ./files:/app/vikunja/files
      - ./db:/db
    networks:
      - arm-net

networks:
  arm-net:
    external: true
