services:
  tailscale-arm:
    image: tailscale/tailscale:latest
    container_name: tailscale-arm
    restart: unless-stopped
    network_mode: host
    environment:
      TS_AUTHKEY: 'tskey-auth-dummy-replace-in-env'
      TS_ROUTES: '192.168.64.0/24'
    volumes:
      - ./state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
